version: '3.4'

services:
  
  geek.web:
    image: geek.web
    container_name: geek.web
    build:
      context: .
      dockerfile: src/GeekComparer.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider http://localhost:80/healthz || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5
    depends_on:
      geek.db:
        condition: service_started
      geek.cache:
        condition: service_started

  geek.db:
    container_name: geek.db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "15432:5432"
    volumes:
      - pg:/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 5s
      retries: 5
  
  geek.cache:
    container_name: geek.cache
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 5s
      retries: 5
    
volumes: 
  cache:
    driver: local
  pg:
    driver: local